<#
.SYNOPSIS
  Wire runbox into the repo this skill has been copied into.

.DESCRIPTION
  Writes a harness\serve.ps1 wrapper, checks the toolchain, and reports what the
  project still has to provide. Deliberately small: the service is a .NET
  file-based app with no project file and the gallery is two static assets beside
  it, so there is nothing to build and nothing to install.

  Safe to re-run. It will not overwrite an existing wrapper unless -Force.

.EXAMPLE
  .\.claude\skills\runbox\install.ps1
  .\.claude\skills\runbox\install.ps1 -Launch "love {game}" -Force
#>
[CmdletBinding()]
param(
    [string]$Launch = '',
    [int]$Port = 7777,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Get-RepoRoot {
    $d = $PSScriptRoot
    while ($d -and -not (Test-Path (Join-Path $d '.git'))) {
        $parent = Split-Path -Parent $d
        if ($parent -eq $d) { break }
        $d = $parent
    }
    if (-not $d -or -not (Test-Path (Join-Path $d '.git'))) { throw "could not find a repo root above $PSScriptRoot" }
    return $d
}

$root = Get-RepoRoot

# Run inside the runbox repo, Get-RepoRoot finds runbox's own root and this would
# install the skill into its own source tree. The workshop is what identifies it:
# a consuming project has the deliverable and none of this.
if ((Test-Path (Join-Path $root 'test.ps1')) -and
    (Test-Path (Join-Path $root 'skills\runbox\SKILL.md'))) {
    throw "this is the runbox repo. The installer belongs in the project you want to instrument: copy skills\runbox into <target>\.claude\skills\runbox and run it from there."
}

$tool = Join-Path $PSScriptRoot 'tool'
$harness = Join-Path $root 'harness'
$wrapper = Join-Path $harness 'serve.ps1'

# The wrapper has to reach serve.cs from the repo root at runtime. Derive that from
# where this script actually sits rather than assuming .claude\skills\runbox, so a
# skill installed under a different name still produces a wrapper that works.
$toolRel = $tool.Substring($root.Length).TrimStart('\', '/')

Write-Output "runbox -> $root"
Write-Output ""

# ---- toolchain ------------------------------------------------------------
$env:Path = [Environment]::GetEnvironmentVariable('Path','Machine') + ';' +
            [Environment]::GetEnvironmentVariable('Path','User')

$sdk = (& dotnet --list-sdks 2>$null | Select-Object -Last 1)
if (-not $sdk) { Write-Output "[!] no .NET SDK found. runbox needs one that supports file-based apps (10.x)." }
else { Write-Output "[+] dotnet sdk: $($sdk.Trim())" }

if (Get-Command ffmpeg -ErrorAction SilentlyContinue) { Write-Output "[+] ffmpeg on PATH" }
else { Write-Output "[-] ffmpeg not on PATH. Runs will index without clips; the gallery still works, with no video." }

# ---- wrapper --------------------------------------------------------------
New-Item -ItemType Directory -Path $harness -Force | Out-Null

if ((Test-Path $wrapper) -and -not $Force) {
    Write-Output "[=] harness\serve.ps1 already exists (use -Force to replace)"
}
else {
    $launchLine = if ($Launch) { "`n    '--launch', '$Launch'," } else { '' }
    $body = @"
<#
  Start the runbox gallery for this repo. Generated by the runbox skill installer.
#>
[CmdletBinding()]
param([int]`$Port = $Port, [string]`$Launch = '$Launch')

`$ErrorActionPreference = 'Stop'
`$root = Split-Path -Parent `$PSScriptRoot
`$serve = Join-Path `$root '$toolRel\serve.cs'

`$serveArgs = @('run', `$serve, '--', '--port', `$Port, '--root', `$root)
if (`$Launch) { `$serveArgs += @('--launch', `$Launch) }

Write-Output "runbox on http://127.0.0.1:`$Port/"
& dotnet @serveArgs
"@
    [System.IO.File]::WriteAllText($wrapper, $body, (New-Object System.Text.UTF8Encoding($false)))
    Write-Output "[+] wrote harness\serve.ps1"
}

# ---- gitignore ------------------------------------------------------------
# Written, not warned about. Run output is large, regenerable and produced on every
# capture, so the gap between "you should ignore this" and actually ignoring it is
# one commit full of clips.
$gi = Join-Path $root '.gitignore'
$needed = @('.harness-out/', '.harness-verdicts.json')

# MEASURED: Get-Content -Raw decodes a BOM-less file with the system ANSI codepage
# and Set-Content -Encoding utf8 writes a BOM, so both corrupt a round trip on 5.1.
$enc = New-Object System.Text.UTF8Encoding($false)
$text = if (Test-Path $gi) { [System.IO.File]::ReadAllText($gi) } else { '' }
$missing = @($needed | Where-Object { $text -notlike "*$_*" })

if (-not $missing) {
    Write-Output "[+] .gitignore already covers run output and verdicts"
}
else {
    $add = "`r`n# runbox: run output and verdicts`r`n" + ($missing -join "`r`n") + "`r`n"
    if ($text -and -not $text.EndsWith("`n")) { $add = "`r`n" + $add }
    [System.IO.File]::WriteAllText($gi, $text + $add, $enc)
    Write-Output "[+] .gitignore: added $($missing -join ', ')"
}

# ---- what the project still owes ------------------------------------------
$outRoot = Join-Path $root '.harness-out'
$hasRuns = (Test-Path $outRoot) -and @(Get-ChildItem $outRoot -Recurse -Filter 'result.json' -ErrorAction SilentlyContinue).Count -gt 0

Write-Output ""
Write-Output "=== next ==="
if ($hasRuns) {
    Write-Output "  .\harness\serve.ps1                 start the gallery"
}
else {
    Write-Output "  This project does not write run output yet. runbox needs:"
    Write-Output "    .harness-out\<game>\<scenario>\<runId>\result.json"
    Write-Output "  with run_at, frames, passed and events. See reference\run-contract.md."
    Write-Output "  Determinism first: fixed tick, seeded RNG, recorded input. Without all"
    Write-Output "  three, frame-locked comparison is meaningless."
}
Write-Output "  .\$toolRel\export.ps1   bake one self-contained file"
